apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  configManagementPlugins: |
    - name: helmfile
      init:
        command: ["argo-cd-helmfile.sh"]
        args: ["init"]
      generate:
        command: ["argo-cd-helmfile.sh"]
        args: ["generate"]
