apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - mountPath: /usr/local/bin/argo-cd-helmfile.sh
              name: custom-tools
              subPath: argo-cd-helmfile.sh
            - mountPath: /usr/local/bin/helmfile
              name: custom-tools
              subPath: helmfile
      initContainers:
        - args:
            - |
              wget -qO /custom-tools/argo-cd-helmfile.sh https://raw.githubusercontent.com/travisghansen/argo-cd-helmfile/master/src/argo-cd-helmfile.sh &&\
              chmod +x /custom-tools/argo-cd-helmfile.sh &&\
              wget -qO /custom-tools/helmfile https://github.com/roboll/helmfile/releases/download/v0.138.7/helmfile_linux_amd64 &&\
              chmod +x /custom-tools/helmfile
          command: [sh, -c]
          image: alpine:3.8
          imagePullPolicy: IfNotPresent
          name: download-tools
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
      volumes:
        - emptyDir: {}
          name: custom-tools
