repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus-blackbox-exporter
    namespace: blackbox-exporter
    chart: prometheus-community/prometheus-blackbox-exporter
    version: 8.2.0
    values:
      - values.yaml
