apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-env
  namespace: grafana
spec:
  encryptedData:
    GF_DATABASE_URL: AgBTwMLM+00HyYlKTKPmXpnQR4KqhBHbFcH6p7Jpn1YWhkMgGfmAvt8Gwcne3vCY1+WKbtkYfZn6F2VQnZzxMH4nGfLyM9599XQal35ESqTJkkh+ogQsMJQUfSy5E4Uq+7VNiMDXbrk7LXbLkHENq9ZQ1jMVdCQssN+Ob3bDmDkw0D5ULbPwNpxliy/MXcJYG9B2MKNyT+o6vd2D5BcpzxXLQfbrYfRP5K9mu2YhPjZrmPyia35NpynhWiOZSnDGwnoZt0CGp9/evDQFT0i82K/YMKbBkB4KiLNn4v1gWbwyY7VgVxuDallmQW7vME3mri0HbdEvZxFqlP4jwm4iqLmejxj7Losw5K/crf8WSKT8gIo5mP+SVmYa4W8Q+1VLaGUpnXHkj3vrDE4rIyQbazRcRYe2yFPti+AAIQKUAWYQ+PiRwGwASrMsKGG0ZgAuoyJ6Jsf+sHGrx6hdF23WJxaHV5GVvXQqKY7MFnDaqPitd/AHL7zhOic4iujnq1f1IA74dz2lnpE3lyTCxnmqr1E8j2Q9cdmyQGvDFwnApyi2FUpie+KUYyadDk6EIELduDuLqsw40dXLCg6IOfgxJ5iUhjHYYucksRrFWUNjezsCGkY6oI7hSNZqYMwvkkw1ndGRxAm8HEC4VQiq2O04EmA+/YOwzfrsKxx4W4dvrkegoUmQIi4YwbsU9CJuSbkvARiLiEZczRupwvjgxLqP/Pi/apZxun6nu8/Ca4OR6ox5Bi6kebAm2ArSKudezw8K61C8
    GF_SESSION_PROVIDER_CONFIG: AgCfHCFXdLTGhQ/Y8V/aNPyx0Fy7dtJ0fBCAYvNoHgwKi/JcDAd/odaQ1oMcuXEyOQwzrgCrNITbSxZh1JSYKL0/2IrfcJxwkHa6btQ9txo1Lis+GENLh30EHvEkhgTatl7uGecmC8HuZx6gWTFqH40PCggNS4MRbyf+utw3bLNcyphjMD5ZBx+bzJDPdUhWrUF4TUWCf+NJt5qANqFYyoDr5Zocf0wZmm+5eDwaaZ0OuQCl1bmJGyefgZxPNR8AILKTvXy9xZNWFPfHD/o7btfRkTdLQqAskZpJHzRnXzvBKqQAuf7YR9w91I8Bhtupms+oKjGlDFqxTpw8qrfzBV0l/L5DQqpYHETV2OYZeZ0hyH1JkeFnAK+JnegpoL8w+jnj4EzzD0o5f/zhoQlQMkfSfYIWtXii19ruk8loIhQ9dZJJ2lQXXnObezVkFLsSzMUh8XCxt3ZVS+Um551tlWvkYxftYJABn10yH1aTOA6R2Uoil0bBbnIcfWGEF0uHotoCYLVQh3W8iFb+hKVg4Ct8oymTg3TVEt4qTVA3BIdIphcjkceXuroHg1sjG7WWdTqlNnCVC17pGwy/jpMFEL+tN6cObeYrX1kNxQzg+fIdYAkbApONTazJcwbrjOt6GqGdUfC7yiy2Np+dT0/ehh0+sfF5HC3KF0BfUKXCKiNsWBWEKI58Qzt3dF6CoVDHD1eSk+u7Nhtk/EY8sNDPxMx6DLC8lIClVfmGGktIDhz4uC6applqbth08RSSASMj
  template:
    metadata:
      creationTimestamp: null
      name: grafana-env
      namespace: grafana
    type: Opaque
