repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana
    namespace: grafana
    forceNamespace: grafana
    chart: grafana/grafana
    values:
      - values.yaml
  - name: custom-resource
    namespace: grafana
    forceNamespace: grafana
    chart: ./resources
