namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.8/manifests/ha/install.yaml

patches:
  - path: patches/argocd-repo-server.yaml
  - path: patches/argocd-cm.yaml
