apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: speedtest-exporter
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: speedtest-exporter
  endpoints:
    - port: http
      interval: 30m
      scrapeTimeout: 60s
  namespaceSelector:
    matchNames:
      - speedtest-exporter
