apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-server
  namespace: argocd
spec:
  project: sinoa
  source:
    repoURL: https://github.com/frauniki/manifests
    targetRevision: HEAD
    path: clusters/aisa/minecraft-server/resources
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
