apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: remo-exporter
  namespace: argocd
spec:
  project: sinoa
  source:
    repoURL: https://github.com/frauniki/manifests
    targetRevision: HEAD
    path: clusters/aisa/remo-exporter/resources
  destination:
    server: "https://kubernetes.default.svc"
    namespace: remo-exporter
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
