repositories:
  - name: sealed-secrets
    url: https://bitnami-labs.github.io/sealed-secrets

releases:
  - name: crd
    chart: ./crds
  - name: sealed-secrets
    namespace: sealed-secrets
    chart: sealed-secrets/sealed-secrets
